### PR TITLE
added background-color & read me

### PR DESCRIPTION
**Pull request by AMI-lang**

### CODE REVIEW

**Comment by jidegithub** [comment]
a fork, very valid approach @AMI-lang

**Comment by AMI-lang** [comment]
Thank you sir, could there be a better or alternative approach though?

**Comment by jidegithub** [comment]
@AMI-lang you don't necessarily have a fork a repo to create a pull request

**Comment by AMI-lang** [comment]
Oh wow, So do u mean I could do all that after cloning ur repo first, or without cloning at all ?  @jidegithub

**Comment by jidegithub** [comment]
@AMI-lang yes, you have clone my repo first.

**Comment by AMI-lang** [comment]
> 

Okay! Now I get it. We’re able to clone your repo without a Fork because you’ve given us **write permissions** right? which allows others to easily create branches off your main? So there was no need for me to fork. But in the case where we don’t have access/permissions , then we have to fork first! Hope my analogy is right sir? Thank you so much @jidegithub

**Pull request closed without merging**
